In [ ]:
import numpy as np
dimensional_array = np.array([1.2, 2.4, 3.5, 4.7, 6.1, 7.2, 8.3, 9.5])
two_dimensional_array=np.array([[1,2],[3,4],[5,6]])
null_matrix=np.arange(5,10)
print(two_dimensional_array)
print(null_matrix)

[[1 2]
 [3 4]
 [5 6]]
[5 6 7 8 9]


In this exercise , created an array with feature and modified labels by random noise

Numpy exercise


In [ ]:
import numpy as np
feature=np.arange(6,21)
label=3*feature+4
l=len(label)
noise=np.random.uniform(-2,2,l)
label=label+noise
print(feature)
print(label)

[ 6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[21.12290951 26.5667663  28.44244563 30.75242868 35.76441707 35.06143579
 38.7139598  44.16956992 44.60011755 50.07029099 50.24444257 55.99730079
 58.26899781 61.04545543 64.788055  ]


Below is the code exercise for pandas data frames , df in a table created in runtime , has a lot of operations to slice and mainly used to randomise data for ml

In [ ]:
import pandas as pd
import math
my_dat=np.random.rand(3,4)
my_data=np.rint(my_dat*100)
my_columns=['Eleanor', 'Chidi', 'Tahani', 'Jason']
my_dataframe = pd.DataFrame(data=my_data, columns=my_columns)
my_dataframe['Janet']=my_dataframe['Tahani']+my_dataframe['Jason']
my_value=my_dataframe.loc[1,'Eleanor']
print(my_dataframe,'\n')
print(my_dataframe.iloc[[1]],'\n')
print(my_value,'\n')

#create duplicate df
my_df_2=pd.DataFrame.copy(my_dataframe)

#other method to slice using row and colums
q=my_df_2['Chidi'][0]
print(q)

#other method to intaite data frame in  a line
my_new_df=pd.DataFrame(data=np.rint(np.random.rand(3,4)*10),columns=['A','B','C','D'])
print(my_new_df,'\n')

   Eleanor  Chidi  Tahani  Jason  Janet
0     27.0   68.0    64.0   34.0   98.0
1      6.0   54.0     9.0   45.0   54.0
2     11.0   77.0    82.0   37.0  119.0 

   Eleanor  Chidi  Tahani  Jason  Janet
1      6.0   54.0     9.0   45.0   54.0 

6.0 

68.0
      A    B    C    D
0   6.0  1.0  3.0  5.0
1  10.0  3.0  6.0  9.0
2   9.0  6.0  1.0  1.0 



In [ ]:
import pandas as pd
import numpy as np
import tensorflow as tf

from matplotlib import pyplot as plt

def build_model(my_learning_rate):
  model = tf.keras.models.Sequential()
  model.add(tf.keras.layers.Dense(units=1,input_shape=(1,)))
  model.compile(optimizer=tf.keras.optimizers.RMSprop(learning_rate=my_learning_rate),loss='mean_squared_error',metrics=[tf.keras.metrics.RootMeanSquaredError()])
  model.summary()
  return model

build_model(1)



Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 1)                 2         
Total params: 2
Trainable params: 2
Non-trainable params: 0
_________________________________________________________________


In [ ]:
def train_model(model,feature,labels,epochs,batch_size):
  history=model.fit(x=feature,y=label,batch_size=batch_size,epochs=epochs)
  trained_weights=model.getweights()[0]
  trained_bias=model.getweights()[1]
  epochs=history.epoch
  hist=pd.DataFrame(history.history)
  rmse=hist['root_mean_squared_error']


In [ ]:
train_sample=[]
train_labels=[]

In [ ]:
#generate data
from sklearn.preprocessing import MinMaxScaler
from random import randint
import numpy as np
import tensorflow as tf


for i in range(200):
  younger_rand=randint(13,64)
  train_sample.append(younger_rand)
  train_labels.append(0)

  old_rand=randint(65,100)
  train_sample.append(old_rand)
  train_labels.append(1)

for i in range(20):
  younger_rand=randint(13,64)
  train_sample.append(younger_rand)
  train_labels.append(1)

  old_rand=randint(65,100)
  train_sample.append(old_rand)
  train_labels.append(0)


train_samples_np=np.array(train_sample)
train_labels_np=np.array(train_labels)



In [ ]:
#scaling
scaler=MinMaxScaler(feature_range=(0,1))
scaled_train_samples=scaler.fit_transform((train_samples_np).reshape(-1,1))


In [ ]:
#build_model
lr=0.01
model=tf.keras.models.Sequential()
model.add(tf.keras.layers.Dense(units=1,input_shape=(1,),activation='relu'))
model.compile(optimizer=tf.keras.optimizers.SGD(learning_rate=lr),loss="mean_squared_error",metrics=[tf.keras.metrics.RootMeanSquaredError()])
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 1)                 2         
Total params: 2
Trainable params: 2
Non-trainable params: 0
_________________________________________________________________


In [ ]:
#train_model
ep=30
batch_s=20
model.fit(x=scaled_train_samples,y=train_labels_np,epochs=ep,batch_size=batch_s)


In [ ]:
#test samples generated random data for test samples as well similar to train samples
test_samples=[]
test_labels=[]

for i in range(10):
  young_rand=randint(13,64)
  test_samples.append(young_rand)
  test_labels.append(1)

  old_rand_t=randint(65,100)
  test_samples.append(old_rand_t)
  test_labels.append(0)

for i in range(40):
  young_rand=randint(13,64)
  test_samples.append(young_rand)
  test_labels.append(0)

  old_rand_t=randint(65,100)
  test_samples.append(old_rand_t)
  test_labels.append(1)

np_test_samples=np.array(test_samples)
np_test_labels=np.array(test_labels)

scaled_test_samples=scaler.fit_transform((np_test_samples).reshape(-1,1))

In [ ]:
from IPython.display import display, Javascript
from google.colab.output import eval_js
from base64 import b64decode

def take_photo(filename='photo.jpg', quality=0.8):
  js = Javascript('''
    async function takePhoto(quality) {
      const div = document.createElement('div');
      const capture = document.createElement('button');
      capture.textContent = 'Capture';
      div.appendChild(capture);

      const video = document.createElement('video');
      video.style.display = 'block';
      const stream = await navigator.mediaDevices.getUserMedia({video: true});

      document.body.appendChild(div);
      div.appendChild(video);
      video.srcObject = stream;
      await video.play();

      // Resize the output to fit the video element.
      google.colab.output.setIframeHeight(document.documentElement.scrollHeight, true);

      // Wait for Capture to be clicked.
      await new Promise((resolve) => capture.onclick = resolve);

      const canvas = document.createElement('canvas');
      canvas.width = video.videoWidth;
      canvas.height = video.videoHeight;
      canvas.getContext('2d').drawImage(video, 0, 0);
      stream.getVideoTracks()[0].stop();
      div.remove();
      return canvas.toDataURL('image/jpeg', quality);
    }
    ''')
  display(js)
  data = eval_js('takePhoto({})'.format(quality))
  binary = b64decode(data.split(',')[1])
  with open(filename, 'wb') as f:
    f.write(binary)
  return filename

In [ ]:
from IPython.display import display, Javascript
from google.colab.output import eval_js
from base64 import b64decode

def take_photo(filename='photo.jpg', quality=0.8):
  js = Javascript('''
    async function takePhoto(quality) {
      const div = document.createElement('div');
      const capture = document.createElement('button');
      capture.textContent = 'Capture';
      div.appendChild(capture);

      const video = document.createElement('video');
      video.style.display = 'block';
      const stream = await navigator.mediaDevices.getUserMedia({video: true});

      document.body.appendChild(div);
      div.appendChild(video);
      video.srcObject = stream;
      await video.play();

      // Resize the output to fit the video element.
      google.colab.output.setIframeHeight(document.documentElement.scrollHeight, true);

      // Wait for Capture to be clicked.
      await new Promise((resolve) => capture.onclick = resolve);

      const canvas = document.createElement('canvas');
      canvas.width = video.videoWidth;
      canvas.height = video.videoHeight;
      canvas.getContext('2d').drawImage(video, 0, 0);
      stream.getVideoTracks()[0].stop();
      div.remove();
      return canvas.toDataURL('image/jpeg', quality);
    }
    ''')
  display(js)
  data = eval_js('takePhoto({})'.format(quality))
  binary = b64decode(data.split(',')[1])
  with open(filename, 'wb') as f:
    f.write(binary)
  return filename

In [ ]:
from IPython.display import Image
try:
  filename = take_photo()
  print('Saved to {}'.format(filename))
  
  # Show the image which was just taken.
  display(Image(filename))
except Exception as err:
  # Errors will be thrown if the user does not have a webcam or if they do not
  # grant the page permission to access it.
  print(str(err))

In [ ]:
from IPython.display import Image
try:
  filename = take_photo()
  print('Saved to {}'.format(filename))
  
  # Show the image which was just taken.
  display(Image(filename))
except Exception as err:
  # Errors will be thrown if the user does not have a webcam or if they do not
  # grant the page permission to access it.
  print(str(err))

model.predict is used to give the exact predicted value(probability) whereas predict_class will round the value and give either 0,1

In [ ]:
#predict
predictions=model.predict(scaled_test_samples,batch_size=7,verbose=0)
roounded_predictions=model.predict_classes(scaled_test_samples,batch_size=7,verbose=0)
for i in predictions:
  print(i)